# Generated by Django 4.0.4 on 2022-04-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=50)),
                ('ostation', models.CharField(max_length=50)),
                ('dstation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
                ('station_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=50)),
                ('train_type', models.CharField(max_length=50)),
                ('train_number', models.CharField(max_length=10)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.route')),
            ],
        ),
        migrations.CreateModel(
            name='Train_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField()),
                ('total_fare', models.IntegerField()),
                ('running_status', models.CharField(max_length=50)),
                ('train_numbe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.trains')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.CharField(max_length=50)),
                ('arrival_time', models.CharField(max_length=50)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.route')),
                ('station_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.station')),
                ('train_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.trains')),
            ],
        ),
    ]
