# Generated by Django 4.0.4 on 2022-04-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_status',
            old_name='train_numbe',
            new_name='train_number',
        ),
    ]
