# Generated by Django 4.0.4 on 2022-04-23 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_rename_train_numbe_train_status_train_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_status',
            name='rid',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trains.route'),
            preserve_default=False,
        ),
    ]
