# Generated by Django 4.0.4 on 2022-04-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0003_train_status_rid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pnr', models.CharField(default=None, max_length=15, primary_key=True, serialize=False)),
                ('book_date', models.DateTimeField(auto_now_add=True)),
                ('train_class', models.CharField(max_length=10)),
                ('ticket_no', models.IntegerField(default=5324)),
                ('seat_no', models.IntegerField()),
                ('date_of_journey', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.route')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.trains')),
            ],
        ),
    ]
