# Generated by Django 4.0.4 on 2022-04-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_of_journey',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr',
            field=models.IntegerField(default=96311, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_no',
            field=models.IntegerField(default=0),
        ),
    ]
