# Generated by Django 4.0.4 on 2022-04-24 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_ticket_date_of_journey_alter_ticket_pnr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reg_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
